/**
 * The response headers every page carries, and the file that applies them to the static
 * tier.
 *
 * **Why this is one module and not a `_headers` file.** Cloudflare Pages states plainly
 * that "custom headers defined in the `_headers` file are not applied to responses
 * generated by Pages Functions". Of 62,466 dog pages, 3,461 are static files and 59,005
 * are rendered by a Function — so a `_headers` file alone would protect 6% of the site
 * while a scanner testing the home page reported everything fixed. The headers are
 * therefore declared once here and applied twice: written into `_headers` by the build,
 * and spread into every `Response` the three Functions return.
 *
 * **What these are and are not worth.** This site has no cookies, no sign-in, no session,
 * no stored user input and no JavaScript. The real exposure they close is small, and only
 * HSTS closes anything a visitor could otherwise suffer. They are cheap hygiene, added
 * 2026-09-02 after a Sucuri report, not a fix for a live risk.
 *
 * @author Yuliya Malinina <julia.malinina@gmail.com>
 */

/**
 * The policy, one directive per line of reasoning.
 *
 * `script-src 'none'` is the unusual one, and it is honest: the only `<script>` on any
 * page is the JSON-LD block, and a script element whose type is not a JavaScript MIME
 * type is a data block that `script-src` does not govern. Almost no site can say this.
 *
 * `style-src-attr 'unsafe-inline'` is the one loosening, and it is load-bearing: the
 * bracket's geometry is 35 inline `style="grid-column:…"` attributes per page, computed
 * server-side precisely so the chart survives scripting being switched off. Splitting
 * `style-src` from `style-src-attr` keeps the stylesheet itself strict — a hash or nonce
 * is not available to a static file served from R2.
 *
 * `frame-ancestors` is here for the licence rather than for clickjacking: there is nothing
 * on these pages to hijack a click into, but framing the catalogue inside another site is
 * not something CC BY-NC-SA contemplates. The club's own domain is allowed so it can embed
 * its own database if it ever wants to.
 */
const CSP = [
  "default-src 'none'",
  "script-src 'none'",
  "object-src 'none'",
  "style-src 'self'",
  "style-src-attr 'unsafe-inline'",
  "img-src 'self'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'self' https://japanesespitz.org https://www.japanesespitz.org",
].join('; ');

/**
 * `max-age` is deliberately one day to begin with.
 *
 * HSTS is sticky: a browser that has seen a year will refuse plain HTTP for this host for
 * a year, whatever happens to the site in between. A day is long enough to be useful and
 * short enough to undo. Raise it once it has been live and uneventful for a while.
 *
 * No `includeSubDomains` and no `preload`: this is a subdomain, and the club's WordPress
 * site and Titan email live on the apex. Neither should be able to inherit a decision made
 * here.
 */
const HSTS = 'max-age=86400';

/** Header name → value, applied identically to both tiers. */
export const SECURITY_HEADERS: Readonly<Record<string, string>> = Object.freeze({
  'content-security-policy': CSP,
  'strict-transport-security': HSTS,
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'strict-origin-when-cross-origin',
});

/**
 * The `_headers` file for the static tier.
 *
 * `/*` matches every path Pages serves as a file. Functions responses are unaffected by
 * this file, which is the whole reason `SECURITY_HEADERS` is exported as well.
 */
export function headersFile(): string {
  return [
    '# Generated by `npm run render:site` — do not edit by hand.',
    '#',
    '# Applies to STATIC responses only. Cloudflare Pages does not apply this file to',
    '# Pages Functions, which render 59,005 of the 62,466 dog pages, the JSON API and',
    '# search — those set the same headers in code, from src/render/headers.ts.',
    '',
    '/*',
    ...Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`),
    '',
  ].join('\n');
}
