#!/usr/bin/env node
/**
 * Vendoring of the pure modules from pedigree-insights.
 *
 * Why this exists: the genetics and traversal code is shared with the desktop
 * application and a fix must never land in only one of the two. Copying without
 * tooling makes divergence invisible; publishing a package adds a release step to
 * a repo that ships on its own cadence. So: copy, but record a hash of every file
 * and fail the tests when a copy no longer matches its source.
 *
 * Usage:
 *   node tools/vendor-lib.mjs           # sync from the source repo, rewrite the manifest
 *   node tools/vendor-lib.mjs --check   # verify the copies match the manifest; exit 1 if not
 *
 * @author Yuliya Malinina <julia.malinina@gmail.com>
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cfg = JSON.parse(readFileSync(join(root, 'vendor.config.json'), 'utf8'));
const manifestPath = join(root, cfg.target, 'MANIFEST.json');
const check = process.argv.includes('--check');

const sha = (buf) => createHash('sha256').update(buf).digest('hex');

function sourceCommit(srcRoot) {
  try {
    return execFileSync('git', ['-C', srcRoot, 'rev-parse', '--short', 'HEAD'], {
      encoding: 'utf8',
    }).trim();
  } catch {
    return null;
  }
}

function fail(msg) {
  console.error(`\n✗ ${msg}\n`);
  process.exit(1);
}

if (check) {
  if (!existsSync(manifestPath)) fail('No vendor manifest. Run `npm run vendor:sync`.');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const drifted = [];
  for (const [file, expected] of Object.entries(manifest.files)) {
    const p = join(root, cfg.target, file);
    if (!existsSync(p)) {
      drifted.push(`${file} — missing`);
      continue;
    }
    const actual = sha(readFileSync(p));
    if (actual !== expected) drifted.push(`${file} — edited in place`);
  }
  if (drifted.length) {
    fail(
      `Vendored modules have drifted:\n  ${drifted.join('\n  ')}\n` +
        'These files are copies. Edit them in pedigree-insights, then run `npm run vendor:sync`.',
    );
  }
  console.log(
    `✓ ${Object.keys(manifest.files).length} vendored modules match the manifest ` +
      `(source ${manifest.sourceCommit ?? 'unknown'}).`,
  );
  process.exit(0);
}

const srcRoot = resolve(root, cfg.source);
if (!existsSync(srcRoot)) {
  fail(
    `Source repository not found at ${cfg.source} (relative to this repo).\n` +
      'The two repositories are expected to sit side by side. Adjust "source" in vendor.config.json.',
  );
}

const commit = sourceCommit(srcRoot);
if (cfg.pinnedCommit && commit && cfg.pinnedCommit !== commit) {
  console.warn(
    `! Source is at ${commit}, vendor.config.json pins ${cfg.pinnedCommit}. Syncing from ${commit}.`,
  );
}

mkdirSync(join(root, cfg.target), { recursive: true });

/**
 * Relative imports are followed, so `files` in the config lists only the entry points a
 * consumer imports directly. Without this, a module can typecheck in the source repo and
 * fail here purely because one of its own dependencies was not on a hand-kept list — which
 * is a stupid way to spend an afternoon.
 */
function relativeImports(source) {
  const out = new Set();
  const re = /\bfrom\s+['"](\.\/[^'"]+)['"]/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    let spec = m[1].slice(2);
    if (!spec.endsWith('.ts')) spec += '.ts';
    out.add(spec);
  }
  return out;
}

const files = {};
const queue = [...cfg.files];
const seen = new Set();
const pulled = [];
while (queue.length > 0) {
  const file = queue.shift();
  if (seen.has(file)) continue;
  seen.add(file);

  const from = join(srcRoot, cfg.sourceSubdir, file);
  if (!existsSync(from)) fail(`Missing in source: ${cfg.sourceSubdir}/${file}`);
  const body = readFileSync(from);
  writeFileSync(join(root, cfg.target, file), body);
  files[file] = sha(body);

  const direct = cfg.files.includes(file);
  if (!direct) pulled.push(file);
  console.log(`  ${file}${direct ? '' : '  (dependency)'}  ${files[file].slice(0, 12)}`);

  for (const dep of relativeImports(body.toString('utf8'))) queue.push(dep);
}
if (pulled.length > 0) {
  console.log(`\n  ${pulled.length} pulled in as transitive dependencies: ${pulled.join(', ')}`);
}

writeFileSync(
  manifestPath,
  JSON.stringify(
    {
      $comment:
        'Generated by tools/vendor-lib.mjs. Do not edit by hand; do not edit the vendored files either.',
      syncedAt: new Date().toISOString().slice(0, 10),
      source: cfg.source,
      sourceCommit: commit,
      files,
    },
    null,
    2,
  ) + '\n',
);

console.log(
  `\n✓ Vendored ${Object.keys(files).length} modules ` +
    `(${cfg.files.length} listed + ${pulled.length} dependencies) from ${cfg.source} @ ${commit ?? 'unknown'}.`,
);
